### PR TITLE
feat: add `Enter`, `Mouse` and `Leave` events

### LINKED ISSUE #123: `mouse-leave` and `mouse-enter` events
`SystemTrayEvent` contains `MenuItemClick LeftClick RightClick RightClick ` event，but hover event is not contain.I think this should also be a commonly used event.

### PR DESCRIPTION
**Pull request by amrbashir**
closes #123

### CODE REVIEW

**Comment by amrbashir** [comment]
@pewsheen as always, can you take care of macOS part? thanks

**Comment by pewsheen** [comment]
> @pewsheen as always, can you take care of macOS part? thanks

The left and right mouse up event is quite unreliable on macOS. It will be ignored when the menu poped up.

**Comment by amrbashir** [comment]
thanks @pewsheen, LGTM

**Comment by nongyehong** [comment]
Ah, so how can I determine the position of my system icon, I think this hover mouse event can expand a lot of functions

**Comment by amrbashir** [comment]
you can call `icon.rect()` to get the position and size of the icon at any given time, also all the events include the position of the cursor when that event was triggered.

**Comment by yume-chan** [comment]
I wonder why double left click support was removed?

**Pull request merged**
